Completed react-accordion-component
jeff-cruz/c0322-code-solutions pull request #122
Opened 2022-05-21 00:44 UTC by jeff-cruz

![Kapture 2022-05-20 at 17 38 20](https://user-images.githubusercontent.com/99565410/169627645-0b760ed7-a3d5-49cf-ac13-9883fbcc8b50.gif)

2022-05-21 00:49 UTC, thebearingedge requested changes

2022-05-21 00:49 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +    }
Clicking on one should open it and close the others, so try re-thinking this if/else statement

2022-05-22 03:00 UTC, jeff-cruz commented
![Kapture 2022-05-21 at 19 59 24](https://user-images.githubusercontent.com/99565410/169676336-f71579d7-0200-4cb8-b723-a8d8f0157be8.gif)

2022-05-22 05:03 UTC, thebearingedge approved these changes

2022-05-23 01:21 UTC, merged