Completed css-canvas-medical challenge
jeff-cruz/c0322-code-solutions pull request #21
Opened 2022-03-20 03:53 UTC by jeff-cruz

![Kapture 2022-03-19 at 20 52 24](https://user-images.githubusercontent.com/99565410/159147382-a73beb35-782b-43b9-ae32-f232aaed6e67.gif)

2022-03-21 19:48 UTC, codingcodymiller requested changes
Hey Jeffrey! I see a lot of usage of the `row` class and a couple of usages of the `column-half` class, but your `row` class doesn't have `display: flex` applied to it, and you applied `display: flex` to a lot of places individually. There would also be more column classes necessary for this layout than just `column-half` if layout classes were being used correctly. Try to go through this and revise your HTML and CSS to make better use of layout classes in their proper format described in the `css-layout-classes` exercise.

2022-03-22 18:31 UTC, jeff-cruz commented
![Kapture 2022-03-22 at 11 29 41](https://user-images.githubusercontent.com/99565410/159551121-491b23e2-c3b3-455e-84c3-c285324ee4a0.gif)

2022-03-22 20:19 UTC, codingcodymiller requested changes

2022-03-22 20:19 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="row">
This is a `row` directly inside a `row`, you can probably just remove this element and make these two `column-half` elements into siblings of the above `column-full`

2022-03-22 20:19 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  flex-wrap: wrap;
Don't pollute your layout classes, you should move `width` and `flex-wrap` to different classes you can add in addition to the `row` class

2022-03-22 20:19 UTC, codingcodymiller commented on css-canvas-medical/styles.css
> +  flex-basis: 75%;
`flex-basis` only works on children of an element set to `display: flex`. You should change this to `max-width`

2022-03-23 19:58 UTC, codingcodymiller approved these changes
Great work!! 🎉

2022-03-23 23:45 UTC, merged